export const ACTIONS = {
  FETCH_MOVIES: "FETCH_MOVIES",
  FETCH_MOVIES_BY_ID: "FETCH_MOVIES_BY_ID",
  SET_SORT_OPTION: "SET_SORT_OPTION",
  SET_GENRE: "SET_GENRE",
  GET_FILTERED_MOVIES: "GET_FILTERED_MOVIES",
  ADD_MOVIE: "ADD_MOVIE",
  UPDATE_MOVIE: "UPDATE_MOVIE",
  DELETE_MOVIE: "DELETE_MOVIE",
  GET_MOVIES_BY_SEARCH_INPUT: "GET_MOVIES_BY_SEARCH_INPUT",
  PUSH_MOVIES_TO_STORE: "PUSH_MOVIES_TO_STORE",
  PUSH_MOVIE_BY_ID: "PUSH_MOVIE_BY_ID",
};

export const REQUEST_STATE = {
  PENDING: "_PENDING",
  SUCCESS: "_SUCCESS",
  ERROR: "_ERROR",
};
