export const ACTIONS = {
    FETCH_MOVIES: 'FETCH_MOVIES',
    SET_SORT_OPTION: 'SET_SORT_OPTION',
    SET_GENRE: 'SET_GENRE',
    GET_FILTERED_MOVIES: 'GET_FILTERED_MOVIES',
}

export const REQUEST_STATE = {
    PENDING: '_PENDING',
    SUCCESS: '_SUCCESS',
    ERROR: '_ERROR',
  }